title: Bot Revolt Militant
description: Un bot Revolt engagé pour l'éducation politique et la solidarité de classe
theme: jekyll-theme-cayman

markdown: kramdown

# Navigation
navigation:
  - title: Accueil
    url: /
  - title: Installation
    url: /installation
  - title: Commandes
    url: /commandes
  - title: Contribution
    url: /contribution
