title: Bot Revolt Militant
description: Un bot Revolt engagé pour l'éducation politique et la solidarité de classe
remote_theme: pages-themes/cayman@v0.2.0
baseurl: "/autogestion"
url: "https://anarchis12.github.io"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

show_downloads: false

# Navigation
navigation:
  - title: Accueil
    url: /
  - title: Installation
    url: /installation
  - title: Commandes
    url: /commandes
  - title: Contribution
    url: /contribution
